from . import models as m
# module: model, singular, plural, columns
REGISTRY={
'leads':(m.Lead,'Lead','Leads',['customer','source','owner','stage','temperature','budget','sla']),
'customers':(m.Customer,'Cliente','Clientes',['first_name','last_name','phone','city','consent']),
'inbox':(m.Conversation,'Conversa','Inbox',['customer','channel','owner','status']),
'activities':(m.Activity,'Interação','Interações',['customer','kind','user','occurred_at']),
'products':(m.Product,'Produto','Produtos',['name','model','category','brand','active']),
'variants':(m.Variant,'Variante','Variantes',['product','capacity','color','condition','price','cost']),
'inventory':(m.Inventory,'Estoque','Estoque',['variant','quantity','reserved','available','sold','minimum']),
'movements':(m.InventoryMovement,'Movimentação','Movimentações',['variant','kind','quantity','reason','created_at']),
'proposals':(m.Proposal,'Proposta','Propostas',['customer','seller','status','total','valid_until']),
'sales':(m.Sale,'Venda','Vendas',['customer','seller','total','payment_method','status','created_at']),
'payments':(m.Payment,'Pagamento','Pagamentos',['sale','amount','method','status','due_at']),
'trades':(m.UsedDevice,'Troca','Trocas',['customer','model','battery','entry_value','total_cost','margin']),
'tasks':(m.Task,'Tarefa','Tarefas',['title','owner','customer','due_at','priority','status']),
'commissions':(m.Commission,'Comissão','Comissões',['sale','user','amount','status']),
'goals':(m.Goal,'Meta','Metas',['name','user','kind','target','start','end']),
'users':(m.User,'Usuário','Usuários',['username','first_name','role','team','is_active','available']),
'teams':(m.Team,'Equipe','Equipes',['name']),
'investments':(m.MarketingSpend,'Investimento','Investimentos de marketing',['campaign','date','amount','notes']),
'sources':(m.Source,'Origem','Origens',['name']),
'campaigns':(m.Campaign,'Campanha','Campanhas',['name','source','investment']),
'stages':(m.Stage,'Etapa','Etapas',['name','position','kind']),
'loss-reasons':(m.LossReason,'Motivo de perda','Motivos de perda',['name']),
'automations':(m.Automation,'Automação','Automações',['name','trigger','action','delay_days','active']),
'integrations':(m.Integration,'Integração','Integrações',['channel','account_id','enabled']),
'company':(m.Company,'Empresa','Empresa',['name','business_start','business_end','sla_minutes']),
'scoring':(m.ScoringRule,'Critério','Lead scoring',['kind','points']),
'commission-rules':(m.CommissionRule,'Regra de comissão','Regras de comissão',['name','product','category','percent','fixed','active']),
'audit':(m.AuditLog,'Evento','Auditoria',['user','entity','action','created_at']),
'notifications':(m.Notification,'Notificação','Notificações',['title','read','created_at']),
'reactivation-campaigns':(m.ReactivationCampaign,'Campanha de reativação','Campanhas de reativação',['name','months','owner'])}
LABELS={'date':'Data','notes':'Observações','campaign':'Campanha','customer':'Cliente','source':'Origem','owner':'Responsável','stage':'Etapa','temperature':'Temperatura','budget':'Orçamento','sla':'SLA','first_name':'Nome','last_name':'Sobrenome','phone':'Telefone','city':'Cidade','consent':'Consentimento','channel':'Canal','status':'Status','name':'Nome','model':'Modelo','category':'Categoria','brand':'Marca','active':'Ativo','capacity':'Capacidade','color':'Cor','condition':'Condição','price':'Preço','cost':'Custo','variant':'Produto / variante','quantity':'Quantidade','reserved':'Reservado','available':'Disponível','sold':'Vendido','minimum':'Mínimo','kind':'Tipo','reason':'Motivo','created_at':'Criado em','seller':'Vendedor','total':'Total','valid_until':'Validade','payment_method':'Pagamento','battery':'Bateria (%)','entry_value':'Entrada','total_cost':'Custo total','margin':'Margem','title':'Título','due_at':'Prazo','priority':'Prioridade','sale':'Venda','user':'Usuário','amount':'Valor','target':'Objetivo','start':'Início','end':'Fim','username':'Login','role':'Perfil','team':'Equipe','is_active':'Ativo','investment':'Investimento','position':'Ordem','trigger':'Gatilho','action':'Ação','delay_days':'Dias','account_id':'Conta','enabled':'Habilitada','business_start':'Abre','business_end':'Fecha','sla_minutes':'SLA (min)','points':'Pontos','product':'Produto','percent':'Percentual','fixed':'Fixa','entity':'Entidade','read':'Lida','months':'Meses','occurred_at':'Data','method':'Método'}
