# Generated by Django 5.2.18 on 2026-10-07 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=False, editable=False)),
                ('image', models.ImageField(upload_to='attachments/')),
            ],
        ),
        migrations.AddField(
            model_name='useddevice',
            name='status',
            field=models.CharField(choices=[('evaluated', 'Avaliado'), ('received', 'Recebido')], default='evaluated', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='useddevice',
            name='stock_variant',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.variant'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('imei', ''), _negated=True), fields=('imei',), name='unique_variant_imei'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(condition=models.Q(('serial', ''), _negated=True), fields=('serial',), name='unique_variant_serial'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='crm.useddevice'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='crm.product'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', True), ('product__isnull', False)), models.Q(('device__isnull', False), ('product__isnull', True)), _connector='OR'), name='attachment_one_parent'),
        ),
    ]
