# Generated by Django 5.2.18 on 2026-10-07 02:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_activity_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingSpend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=False, editable=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do investimento')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Investimento realizado')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.campaign', verbose_name='Campanha')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
