# Generated by Django 5.2.18 on 2026-10-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_marketingspend'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Telefone'),
        ),
    ]
