# Generated by Django 5.2.18 on 2026-10-07 02:11

import django.db.models.deletion
from django.db import migrations, models


def initialize_roles(apps,schema_editor):
    Role=apps.get_model('crm','Role')
    for code,name in [('admin','Administrador'),('manager','Gestor'),('sdr','SDR'),('seller','Vendedor'),('after','Pós-venda')]:
        Role.objects.using(schema_editor.connection.alias).get_or_create(code=code,defaults={'name':name})

class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_normalize_existing_contacts'),
    ]

    operations = [
        migrations.RunPython(initialize_roles,migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='sdr', on_delete=django.db.models.deletion.PROTECT, to='crm.role', to_field='code', verbose_name='Perfil'),
        ),
    ]
