# Generated by Django 5.2.18 on 2026-10-07 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.CharField(default='#6558f5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Informe uma cor hexadecimal, por exemplo #6558f5.')], verbose_name='Cor principal'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(default='#6558f5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Informe uma cor hexadecimal, por exemplo #6558f5.')], verbose_name='Cor'),
        ),
    ]
