# Generated by Django 5.2.18 on 2026-10-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_company_color_alter_stage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='qualified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='allows_sdr',
            field=models.BooleanField(default=False, verbose_name='SDR pode mover para esta etapa'),
        ),
        migrations.AddField(
            model_name='stage',
            name='behavior',
            field=models.CharField(choices=[('standard', 'Padrão'), ('new', 'Entrada de lead'), ('proposal', 'Proposta enviada'), ('negotiation', 'Negociação'), ('payment', 'Pagamento')], default='standard', max_length=20, verbose_name='Função da etapa'),
        ),
        migrations.AddField(
            model_name='stage',
            name='qualifies_lead',
            field=models.BooleanField(default=False, verbose_name='Qualifica o lead'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(condition=models.Q(('behavior', 'standard'), _negated=True), fields=('behavior',), name='single_stage_behavior'),
        ),
    ]
